server_address: 127.0.0.1:8088
pretrained_name_or_path: wego-hansu/piper_smolvla_teleop_033_C
policy_type: smolvla
policy_device: cuda
actions_per_chunk: 50
chunk_size_threshold: 0.8
aggregate_fn_name: average
debug_visualize_queue_size: false
task: "Pick the car and put in the box"
fps: 30
action_log: true
obs_log: true
client_mode: TeleopMode
verbose: false
robot:
  type: piper_follower
  port: can_follower
  id: black
  cameras:
    top:
      type: opencv
      index_or_path: /dev/video2
      width: 640
      height: 480
      fps: 30
    hand:
      type: opencv
      index_or_path: /dev/video4
      width: 640
      height: 480
      fps: 30